const assert = require('assert');
const fs = require('fs');
const path = require('path');

const root = path.join(__dirname, '..');
const repoRoot = path.join(root, '..');
const mainJs = fs.readFileSync(path.join(root, 'js', 'main.js'), 'utf8');
const authJs = fs.readFileSync(path.join(root, 'js', 'auth.js'), 'utf8');
const apiJs = fs.readFileSync(path.join(root, 'js', 'api.js'), 'utf8');
const adminEmployeesJs = fs.readFileSync(path.join(root, 'js', 'admin-employees.js'), 'utf8');
const indexHtml = fs.readFileSync(path.join(root, 'index.html'), 'utf8');
const mainCss = fs.readFileSync(path.join(root, 'css', 'main.css'), 'utf8');
const modalCss = fs.readFileSync(path.join(root, 'css', 'modal.css'), 'utf8');
const backendAuthJs = fs.readFileSync(path.join(repoRoot, 'apps-script-absensi', 'Auth.js'), 'utf8');
const backendEmployeeJs = fs.readFileSync(path.join(repoRoot, 'apps-script-absensi', 'Employee.js'), 'utf8');
const backendDatabaseJs = fs.readFileSync(path.join(repoRoot, 'apps-script-absensi', 'Database.js'), 'utf8');

assert(backendDatabaseJs.includes('mustChangePassword'), 'Employees sheet should include mustChangePassword column');
assert(backendAuthJs.includes('hashPasswordData'), 'backend should hash stored passwords');
assert(backendAuthJs.includes('verifyPasswordData'), 'backend should verify hashed and legacy plaintext passwords');
assert(backendAuthJs.includes('validateNewPasswordData'), 'backend should validate password strength');
assert(backendAuthJs.includes("mustChangePassword: parseBooleanData"), 'login should return mustChangePassword state');
assert(backendAuthJs.includes('migratePasswordHashIfNeededData'), 'legacy plaintext passwords should migrate after successful login/change');
assert(backendAuthJs.includes("mustChangePassword: false"), 'successful password change should clear mustChangePassword');
assert(backendAuthJs.includes('normalizeChangePasswordRoleData'), 'backend password change should use role to avoid Users/Employees id collisions');
assert(backendAuthJs.includes("normalizedRole === 'karyawan'"), 'employee password changes should target Employees directly');
assert(backendAuthJs.includes("normalizedRole === 'admin' || normalizedRole === 'pemilik'"), 'admin and owner password changes should target Users directly');
assert(backendAuthJs.includes('findEmployeeForLoginData'), 'employee login should support lookup by email or employee ID');
assert(backendAuthJs.includes("String(employee.id || '').toLowerCase().trim() === normalizedIdentifier"), 'employee login should compare employee ID case-insensitively');
assert(backendAuthJs.includes('Email atau ID karyawan tidak ditemukan'), 'employee login error should match email-or-ID behavior');
assert(backendEmployeeJs.includes("data.mustChangePassword = true"), 'new employees should be forced to change the default password');
assert(backendEmployeeJs.includes('sanitizeEmployeeForClientData'), 'employee list should strip password before returning to frontend');
assert(backendEmployeeJs.includes('delete clean.password'), 'employee API should not expose password');

assert(authJs.includes('mustChangePassword'), 'frontend auth should carry mustChangePassword from login response');
assert(authJs.includes("document.getElementById('profile-employee-id').textContent"), 'employee profile should render the employee ID');
assert(authJs.includes('enforcePasswordChange'), 'frontend should enforce first-login password change');
assert(authJs.includes('validateNewPassword'), 'frontend should validate password before sending to backend');
assert(authJs.includes('Password baru minimal 8 karakter'), 'frontend should explain password length requirement');
assert(authJs.includes('Password baru harus mengandung huruf dan angka'), 'frontend should explain letter and number requirement');
assert(authJs.includes('Password baru tidak boleh sama dengan password default'), 'frontend should reject default password');
assert(authJs.includes('Karyawan wajib mengganti password'), 'frontend should block forced-password users from dashboard');
assert(authJs.includes('closeProfileModal()'), 'forced password modal close should be guarded');
assert(indexHtml.includes('onclick="auth.closeProfileModal()"'), 'profile modal close button should use guarded auth close helper');
assert(indexHtml.includes('Aturan password baru'), 'change password form should show password rules');
assert(indexHtml.includes('Minimal 8 karakter'), 'password rules should show minimum length');
assert(indexHtml.includes('Harus mengandung huruf dan angka'), 'password rules should show letter and number requirement');
assert(indexHtml.includes('password default 12345'), 'password rules should warn against default password');
assert(modalCss.includes('.password-rules'), 'password rules should be styled in the profile modal');
assert(/\.toast-container\s*\{[^}]*z-index:\s*5000;/s.test(mainCss), 'toast should appear above profile modal notifications');
assert(/@media\s*\(max-width:\s*576px\)\s*\{[^}]*\.toast-container\s*\{[^}]*left:\s*12px;[^}]*right:\s*12px;/s.test(mainCss), 'mobile toast should be full-width and visible above forms');
assert(mainJs.includes('DEFAULT_TOAST_DURATION'), 'toast duration should be centralized and longer than the old default');
assert(/show\(message,\s*type\s*=\s*'info',\s*title\s*=\s*'',\s*duration\s*=\s*DEFAULT_TOAST_DURATION\)/.test(mainJs), 'toast.show should use the longer default duration');
assert(mainJs.includes('data-toast-key'), 'toast should deduplicate identical active messages');
assert(mainJs.includes('toastEl.addEventListener'), 'toast should be dismissible by user touch/click as well as the close button');
assert(indexHtml.includes('id="btn-change-password"'), 'change password button should have a stable id for responsive and loading state');
assert(authJs.includes('isChangingPassword'), 'change password flow should guard against double submit notifications');
assert(modalCss.includes('#btn-change-password'), 'change password button should have responsive modal styling');
assert(apiJs.includes('async changePassword(userId, oldPassword, newPassword, userEmail, userRole)'), 'API should send user email and role for password validation');
assert(apiJs.includes('userRole'), 'API should include role when changing password');
assert(/id="emp-password"[^>]*readonly/.test(indexHtml), 'new employee default password should be locked in the form');
assert(indexHtml.includes('Password awal: 12345. Karyawan wajib mengganti password setelah login pertama.'), 'new employee password note should explain first-login password change');
assert(!indexHtml.includes('Ubah jika perlu'), 'new employee password note should not suggest changing the default password');
assert(adminEmployeesJs.includes("document.getElementById('emp-password').value = ''"), 'edit employee should not show existing password');
assert(adminEmployeesJs.includes("document.getElementById('emp-password').readOnly = false"), 'edit employee password reset field should remain editable');
assert(adminEmployeesJs.includes("document.getElementById('emp-password').readOnly = true"), 'add employee default password should be locked');
assert(adminEmployeesJs.includes('Reset password'), 'admin password field should be reset-only in edit mode');

console.log('password security tests passed');
